apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medical-ai
  template:
    metadata:
      labels:
        app: medical-ai
    spec:
      containers:
      - name: medical-ai
        image: your-docker-username/medical-ai:latest
        ports:
        - containerPort: 8000
